apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-bot
  namespace: default
  labels:
    app: trading-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-bot
  template:
    metadata:
      labels:
        app: trading-bot
    spec:
      containers:
      - name: trading-bot
        image: trading-bot:latest
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 3000
        
        # Load all variables from ConfigMap
        envFrom:
        - configMapRef:
            name: trading-bot-config
        
        # Load all variables from Secret
        - secretRef:
            name: trading-bot-secrets
