apiVersion: v1
kind: Service
metadata:
  name: trading-bot-service
  namespace: default
  labels:
    app: trading-bot
spec:
  type: NodePort
  selector:
    app: trading-bot
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
